---
- hosts: all
  vars:
    etc_hosts_add_all_hosts: true
    etc_hosts_pri_dns_name: "{{ pri_domain_name }}"
    pri_domain_name: test.vagrant.local
  tasks:
    - name: Include ansible-etc-hosts
      include_role:
        name: ansible-etc-hosts
    - name: Include ansible-ntp
      include_role:
        name: ansible-ntp
    - name: Include ansible-timezone
      include_role:
        name: ansible-timezone
    - name: Include ansible-bootstrap-python
      include_role:
        name: ansible-bootstrap-python

- hosts: master_nodes
  vars:
    apache2_install_php: true
    pdns_auth_enable_web_server: true
    pdns_recursor_port: 5300
    pri_domain_name: test.vagrant.local
  tasks:
    - name: Include ansible-apache2
      import_role:
        name: ansible-apache2
    - name: Include ansible-mysql
      include_role:
        name: ansible-mysql
    - name: Include ansible-powerdns-authoritative
      include_role:
        name: ansible-powerdns-authoritative
    - name: Include ansible-powerdns-recursor
      include_role:
        name: ansible-powerdns-recursor

- hosts: slave_nodes
  vars:
    apache2_install_php: true
    pdns_recursor_port: 5300
    pri_domain_name: test.vagrant.local
  tasks:
    - name: Include ansible-apache2
      import_role:
        name: ansible-apache2
    - name: Include ansible-mysql
      include_role:
        name: ansible-mysql
    - name: Include ansible-powerdns-authoritative
      include_role:
        name: ansible-powerdns-authoritative
    - name: Include ansible-powerdns-recursor
      include_role:
        name: ansible-powerdns-recursor
